channels:
  - conda-forge
  # - defaults

dependencies:
  - python=3.6*
  - gdal>2.1
  - poppler<0.66
  - cftime
  - mock = 2.0.0
  - pip
  - pip:
    # - sentinelhub
    - h5py
    - python-dateutil
    # - netCDF4==1.2.7
    - git+https://github.com/Unidata/netcdf4-python/tree/v1.4.2rel
    # - pyyaml
    # - matplotlib
    # - xarray
    - sphinxcontrib-bibtex
    - shapely
    - pyproj
    - scipy

  #   - very-good-setuptools-git-version



